# Generated by Django 4.1.7 on 2023-03-04 07:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_subcategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/category/'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/subcategory/'),
        ),
        migrations.CreateModel(
            name='ProductPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.subcategorymodel', verbose_name='CATEGORY_ID'),
        ),
    ]
