# Generated by Django 4.1.7 on 2023-03-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productmodel_code_alter_productmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='subcategory_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
